import React from 'react'

const page = () => {
  return (
    <div>
      this is about page
    </div>
  )
}

export default page

export const metadata = {
  title: "Created about page",
  description: "Generated by about page author",
};//this will show title and description of page
